# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy everything in the current folder (your project)
COPY . .

RUN dotnet restore BackEnd.csproj
RUN dotnet publish BackEnd.csproj -c Release -o /app/publish

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .

# Allow Render to use dynamic port
ENV ASPNETCORE_URLS=http://

ENTRYPOINT ["dotnet", "BackEnd.dll"]


